name: Build LaTeX Resume

on:
  push:
    branches:
      - main 

permissions: 
  contents: write
  pages: write
  id-token: write 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Compile LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: resume.tex 
        args: -pdflatex -file-line-error -interaction=nonstopmode

    - name: Upload PDF to Artifacts (for debugging/download)
      uses: actions/upload-artifact@v4
      with:
        name: resume-pdf
        path: resume.pdf 

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: . 
        keep_files: false 
